name: 배포

on:
  push:
    branches:
      - main

jobs:
  Static-HTML-Deplyoing-with-API-key-Hiding:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v1
              
      - name: Github pages 배포
        run: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          api_key: ${{ secrets.API_KEY }}
