name: 배포

on:
  push:
    branches:
      - main
jobs:
  get-api-key:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: node 설치
        uses: actions/setup-node@v1
        
      - name: npm 설치
        run: npm install
        
      - name: Github pages 배포
        uses: LEE-NS/WEEK1_team_introduce_page@main
        env:
          API_KEY: ${{secrets.API_KEY}}
