name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: LEE-NS/WEEK1_team_introduce-page@4.1.5
      with:
        branch: gh-pages
        folder: build
        token: ${{ secrets.GITHUB_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        APP_ID: ${{ secrets.APP_ID }}
