name: apiKey

on:
  push:
    branches:
      - main
jobs:
  get-api-key:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
        env:
          API_KEY: ${{secrets.API_KEY}}
